name: Docker Image CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  dockerTag: latest

jobs:

  dockerize_app:
    name: Setup Agent > Build Vite App > Build Docker Image > Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              
      - name: Setup dockerTag to Staging
        if: github.ref_name == 'develop'
        run: |
          echo "dockerTag=dev" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: display current folder
        shell: bash
        run: |
          ls

      - name: Build project
        run: npm run build

      - name: Build and push DockerImage
        run: docker build --platform linux/arm64  --file ./Dockerfile --tag dercraker0/react-map:dev --push .

        
  deploy:
    name: Call portainer to deploy new versions of Docker
    runs-on: ubuntu-latest
    needs: dockerize_app
    steps:
      - name: PUT Request Action to update Stack - STAGING
        uses: fjogeleit/http-request-action@v1.13.0
        with:
          url: 'http://portainer.antoinecapitain.fr/api/stacks/6?endpointId=2'
          method: 'PUT'
          timeout: 20000
          customHeaders: '{ "x-api-key": "ptr_K6DgaD8nqwYk0PyCIaVNJZ4ugZe3jrZCRTJ4wBw0dec=" }'
          data: '${{ vars.PORTAINER_UPDATE_STACK_REACT_MAP}}'
